//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IbreastCare.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BW
    {
        public int BWId { get; set; }
        public Nullable<double> BW1 { get; set; }
        public Nullable<double> BMI { get; set; }
        public System.DateTime InputDate { get; set; }
        public int MyId { get; set; }
        public Nullable<System.DateTime> MeasureDate { get; set; }
    
        public virtual Personal_Data Personal_Datas { get; set; }
    }
}
