//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IbreastCare.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyOperation
    {
        public int MyOpeId { get; set; }
        public int MyId { get; set; }
        public Nullable<int> OpeTypeId { get; set; }
    
        public virtual OperationType OperationType { get; set; }
        public virtual Personal_Datas Personal_Datas { get; set; }
    }
}
