//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IbreastCare.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal_Data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal_Data()
        {
            this.MyOperations = new HashSet<MyOperation>();
            this.MyTreats = new HashSet<MyTreat>();
        }
    
        public int MyId { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public Nullable<double> Height { get; set; }
        public string Menopause { get; set; }
        public string CellType { get; set; }
        public string ER { get; set; }
        public string PR { get; set; }
        public string Her { get; set; }
        public string OperationType { get; set; }
        public string TreatPlan { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyOperation> MyOperations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyTreat> MyTreats { get; set; }
    }
}
