//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IbreastCare.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SymptomDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SymptomDetail()
        {
            this.MySymptoms = new HashSet<MySymptom>();
        }
    
        public int SymptomDetailID { get; set; }
        public int SymptomID { get; set; }
        public int SeverityLevelID { get; set; }
        public string Description { get; set; }
    
        public virtual Symptom Symptom { get; set; }
        public virtual SeverityLevel SeverityLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MySymptom> MySymptoms { get; set; }
    }
}
